# Generated by Django 3.2.7 on 2022-03-26 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0001_initial'),
        ('medical_assistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('ReportID', models.IntegerField(primary_key=True, serialize=False)),
                ('Appointment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='receptionist.doctorpatientassignment')),
                ('MedicalAssistant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='medical_assistant.medicalassistant')),
            ],
        ),
    ]
