# Generated by Django 3.2.7 on 2022-03-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardclerk', '0002_ward_warddetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warddetails',
            old_name='WardNo',
            new_name='Ward',
        ),
        migrations.AddField(
            model_name='ward',
            name='WardType',
            field=models.CharField(default='usual', max_length=45),
        ),
        migrations.AddField(
            model_name='wardclerk',
            name='contact',
            field=models.CharField(default=None, max_length=13),
        ),
    ]
