# Generated by Django 3.2.7 on 2022-03-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Age',
            field=models.IntegerField(default=None),
        ),
    ]
