# Generated by Django 3.2.7 on 2022-03-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Height',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AddField(
            model_name='patient',
            name='Weight',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AddField(
            model_name='patient',
            name='contact',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
