# Generated by Django 3.2.7 on 2022-03-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='department',
            field=models.CharField(default=None, max_length=45),
        ),
        migrations.AddField(
            model_name='doctor',
            name='status',
            field=models.CharField(default=None, max_length=45),
        ),
    ]
