# Generated by Django 3.2.7 on 2022-03-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_rename_department_doctor_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='contact',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
